### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by trevorlasn** [lwz7512/hexo-html-syncer#1]
I'm getting this error when trying to sync my Medium articles. Any ideas why this might be happening?

```
TypeError: Cannot read property 'split' of undefined
    at Node.<anonymous> (/Users/indreklasn/Work/strilliant-blog/node_modules/hexo-html-syncer/lib/convertor.js:40:45)
    at initialize.exports.each (/Users/indreklasn/Work/strilliant-blog/node_modules/cheerio/lib/api/traversing.js:300:24)
    at Request._callback (/Users/indreklasn/Work/strilliant-blog/node_modules/hexo-html-syncer/lib/convertor.js:39:16)
    at Request.self.callback (/Users/indreklasn/Work/strilliant-blog/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.<anonymous> (/Users/indreklasn/Work/strilliant-blog/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (/Users/indreklasn/Work/strilliant-blog/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by lwz7512** [comment]
Can you give me the URL which cause the error? let me take a debug.

**Comment by lwz7512** [comment]
@indreklasn Hi dear, I fixed the error, please update it, and retry!

**Comment by trevorlasn** [comment]
I was using a Medium blog post URL. Thanks, I'll try it. :)
